Rdtk implementation
SamiFdev/CryptoTracker pull request #4
Opened 2022-07-08 22:12 UTC by SamiFdev

toolkit seems to be working fine, just having the issue with it doing the second api request.

2022-07-11 22:34 UTC, SamiFdev commented
Added a slice for single coin search. Current issue seems to be getting the "id" back from the search. Looked into it and I believe it's passed correctly inside the asyncThunk. "id" just keeps coming back as undefined. Spent a few hours trying to trouble shoot this which leads me to think it's just a logical thing I am overlooking atm. 

In main content component I have the "searched coin" setting and console logging (just realized its commented out but still is working). So the state is updating to read my searched coin in the input field. I think its all just broken because of my asyncThunk function inside of singleCoinSlice.js. 

In plain english, what I think is happening in main content, is I am setting a searched coin and firing off the fetchSingleCoin function trying to pass in the searched coin but must be doing it incorrectly. I toyed around with a lot all afternoon and this is what I ended up with after undoing and redoing for awhile after research. If you find the solution i'd love comments on what It is so I can correct it tomorrow Thanks.

2022-07-12 19:17 UTC, arfusop requested changes
Small changes

2022-07-12 19:17 UTC, arfusop commented on src/components/MainContent/index.js
> +    const [searchedCoin, setSearhedCoin] = useState("");
Typo...
`setSearhedCoin` -> `setSearchedCoin`

2022-07-12 19:17 UTC, arfusop commented on src/components/MainContent/index.js
> +                    onChange={(e) => setSearhedCoin(e.target.value)}
Move this out of the onChange into its own function.

```
const handleInputChange = e =>
...
<input ... onChange={handleInputChange}
```

2022-07-12 19:17 UTC, arfusop commented on src/features/singleCoinSlice.js
>          console.log("test", id);
Delete the log

2022-07-12 19:17 UTC, arfusop commented on src/index.js
> +// import { Provider } from "react-redux";
Delete comments

2022-07-12 20:23 UTC, arfusop requested changes

2022-07-12 20:23 UTC, arfusop commented on src/components/MainContent/index.js
> +        <section>
Noticed this now, you added a section without a class that just wraps your div.searchBarContainer

Why have a double container? Either add the class to the section and delete the div (which is what I'd do) or remove the section. Having both is unneeded semantically, and structurally.

2022-07-12 20:23 UTC, arfusop commented on src/utils/api.js
> +// import axios from "axios";
Remove comments

2022-07-12 21:04 UTC, arfusop approved these changes
On pull requests, mark each comment as resolved if you've addressed and made a fix for them. Every comment i've left is technically left open on your PR. Helps everyone involved in the PR if you mark as resolved everything you hit on when you re-request for a fresh review.

2022-07-12 21:06 UTC, merged